-- SQL Schema to initialize the DHL Games Day 2026 Database on Supabase
-- Copy and paste this script directly into your Supabase SQL Editor (https://supabase.com) and click 'Run'

-- Disable row-level security by default briefly during setup, to make sure everything runs cleanly
-- DROP tables if you want a complete clean reset:
-- DROP TABLE IF EXISTS public.matches CASCADE;
-- DROP TABLE IF EXISTS public.participants CASCADE;
-- DROP TABLE IF EXISTS public.admin_users CASCADE;
-- DROP TABLE IF EXISTS public.event_settings CASCADE;
-- DROP TABLE IF EXISTS public.organization_settings CASCADE;
-- DROP TABLE IF EXISTS public.events CASCADE;

-- ========================================================
-- 1. Create Events Table
-- ========================================================
CREATE TABLE IF NOT EXISTS public.events (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    khmer_name TEXT,
    date TEXT,
    description TEXT,
    sports JSONB NOT NULL DEFAULT '[]'::jsonb,
    theme_color TEXT DEFAULT 'dhl',
    created_by TEXT NOT NULL,
    show_public_teams BOOLEAN DEFAULT false,
    is_enrolment_enabled BOOLEAN DEFAULT true,
    organization_slug TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Index for organization and event fetching lookup
CREATE INDEX IF NOT EXISTS idx_events_organization_slug ON public.events(organization_slug);

-- ========================================================
-- 2. Create Matches Table (using text for dynamic sport types)
-- ========================================================
CREATE TABLE IF NOT EXISTS public.matches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT REFERENCES public.events(id) ON DELETE CASCADE,
    created_by TEXT,
    sport_name TEXT NOT NULL,
    match_label TEXT DEFAULT 'Regular Match',
    team_a TEXT NOT NULL,
    team_b TEXT NOT NULL,
    score_a INTEGER DEFAULT 0 NOT NULL,
    score_b INTEGER DEFAULT 0 NOT NULL,
    status TEXT CHECK (status IN ('Upcoming', 'Live', 'Finished')) DEFAULT 'Upcoming' NOT NULL,
    scheduled_date TEXT,
    scheduled_time TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Performance indices
CREATE INDEX IF NOT EXISTS idx_matches_event_id ON public.matches(event_id);
CREATE INDEX IF NOT EXISTS idx_matches_sport_name ON public.matches(sport_name);
CREATE INDEX IF NOT EXISTS idx_matches_status ON public.matches(status);

-- Automated updated_at trigger function
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = TIMEZONE('utc', NOW());
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_matches_updated_at ON public.matches;
CREATE TRIGGER update_matches_updated_at
    BEFORE UPDATE ON public.matches
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

-- ========================================================
-- 3. Create Participants/Athletes/Teams Table
-- ========================================================
CREATE TABLE IF NOT EXISTS public.participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT REFERENCES public.events(id) ON DELETE CASCADE,
    created_by TEXT,
    name TEXT NOT NULL,
    sport_type TEXT NOT NULL,
    is_team BOOLEAN DEFAULT FALSE NOT NULL,
    team_id TEXT, -- Store raw text or bigints. To allow simple local references, we use TEXT.
    photo_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Indexes for speedy roster grouping and category queries
CREATE INDEX IF NOT EXISTS idx_participants_event_id ON public.participants(event_id);
CREATE INDEX IF NOT EXISTS idx_participants_sport_type ON public.participants(sport_type);
CREATE INDEX IF NOT EXISTS idx_participants_is_team ON public.participants(is_team);

DROP TRIGGER IF EXISTS update_participants_updated_at ON public.participants;
CREATE TRIGGER update_participants_updated_at
    BEFORE UPDATE ON public.participants
    FOR EACH ROW
    EXECUTE PROCEDURE update_updated_at_column();

-- ========================================================
-- 4. Create Admin Users Table
-- ========================================================
CREATE TABLE IF NOT EXISTS public.admin_users (
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL,
    name TEXT NOT NULL,
    role TEXT CHECK (role IN ('admin', 'super_admin')) NOT NULL,
    status TEXT CHECK (status IN ('pending', 'approved', 'rejected')) NOT NULL,
    password_plain TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- ========================================================
-- 5. Create Event Settings Table
-- ========================================================
CREATE TABLE IF NOT EXISTS public.event_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- ========================================================
-- 6. Create Organization Settings Table
-- ========================================================
CREATE TABLE IF NOT EXISTS public.organization_settings (
    id TEXT PRIMARY KEY DEFAULT 'current',
    name TEXT NOT NULL,
    logo_url TEXT,
    slug TEXT NOT NULL,
    tagline TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    website TEXT,
    address TEXT,
    footer_motto TEXT,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL
);

-- Insert fallback organization value if it doesn't exist
INSERT INTO public.organization_settings (id, name, logo_url, slug, tagline, contact_email, contact_phone, website, address, footer_motto)
VALUES (
    'current',
    'DHL Express Cambodia',
    'https://logos-world.net/wp-content/uploads/2020/08/DHL-Logo.png',
    'dhl-games',
    'Excellence. Simply delivered.',
    'kh.info@dhl.com',
    '+855 23 999 444',
    'https://www.dhl.com',
    'Phnom Penh, Cambodia',
    'Excellence. Simply delivered.'
) ON CONFLICT (id) DO NOTHING;

-- ========================================================
-- 7. Enable Row Level Security (RLS) on ALL tables
-- ========================================================
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.matches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.event_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.organization_settings ENABLE ROW LEVEL SECURITY;

-- ========================================================
-- 8. Create Permissive Public Security Policies for Quick Testing & Full Sync
-- ========================================================

-- EVENTS policies
DROP POLICY IF EXISTS "Allow read events" ON public.events;
DROP POLICY IF EXISTS "Allow insert events" ON public.events;
DROP POLICY IF EXISTS "Allow update events" ON public.events;
DROP POLICY IF EXISTS "Allow delete events" ON public.events;
CREATE POLICY "Allow read events" ON public.events FOR SELECT USING (true);
CREATE POLICY "Allow insert events" ON public.events FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update events" ON public.events FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow delete events" ON public.events FOR DELETE USING (true);

-- MATCHES policies
DROP POLICY IF EXISTS "Allow read matches" ON public.matches;
DROP POLICY IF EXISTS "Allow insert matches" ON public.matches;
DROP POLICY IF EXISTS "Allow update matches" ON public.matches;
DROP POLICY IF EXISTS "Allow delete matches" ON public.matches;
CREATE POLICY "Allow read matches" ON public.matches FOR SELECT USING (true);
CREATE POLICY "Allow insert matches" ON public.matches FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update matches" ON public.matches FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow delete matches" ON public.matches FOR DELETE USING (true);

-- PARTICIPANTS policies
DROP POLICY IF EXISTS "Allow read participants" ON public.participants;
DROP POLICY IF EXISTS "Allow insert participants" ON public.participants;
DROP POLICY IF EXISTS "Allow update participants" ON public.participants;
DROP POLICY IF EXISTS "Allow delete participants" ON public.participants;
CREATE POLICY "Allow read participants" ON public.participants FOR SELECT USING (true);
CREATE POLICY "Allow insert participants" ON public.participants FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update participants" ON public.participants FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow delete participants" ON public.participants FOR DELETE USING (true);

-- ADMIN USERS policies
DROP POLICY IF EXISTS "Allow read admin_users" ON public.admin_users;
DROP POLICY IF EXISTS "Allow insert admin_users" ON public.admin_users;
DROP POLICY IF EXISTS "Allow update admin_users" ON public.admin_users;
DROP POLICY IF EXISTS "Allow delete admin_users" ON public.admin_users;
CREATE POLICY "Allow read admin_users" ON public.admin_users FOR SELECT USING (true);
CREATE POLICY "Allow insert admin_users" ON public.admin_users FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update admin_users" ON public.admin_users FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow delete admin_users" ON public.admin_users FOR DELETE USING (true);

-- EVENT SETTINGS policies
DROP POLICY IF EXISTS "Allow read event_settings" ON public.event_settings;
DROP POLICY IF EXISTS "Allow insert event_settings" ON public.event_settings;
DROP POLICY IF EXISTS "Allow update event_settings" ON public.event_settings;
DROP POLICY IF EXISTS "Allow delete event_settings" ON public.event_settings;
CREATE POLICY "Allow read event_settings" ON public.event_settings FOR SELECT USING (true);
CREATE POLICY "Allow insert event_settings" ON public.event_settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update event_settings" ON public.event_settings FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow delete event_settings" ON public.event_settings FOR DELETE USING (true);

-- ORGANIZATION SETTINGS policies
DROP POLICY IF EXISTS "Allow read organization_settings" ON public.organization_settings;
DROP POLICY IF EXISTS "Allow insert organization_settings" ON public.organization_settings;
DROP POLICY IF EXISTS "Allow update organization_settings" ON public.organization_settings;
DROP POLICY IF EXISTS "Allow delete organization_settings" ON public.organization_settings;
CREATE POLICY "Allow read organization_settings" ON public.organization_settings FOR SELECT USING (true);
CREATE POLICY "Allow insert organization_settings" ON public.organization_settings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update organization_settings" ON public.organization_settings FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow delete organization_settings" ON public.organization_settings FOR DELETE USING (true);
